source "http://rubygems.org"
# gem "rake", "0.8.7"
# gem "net-ssh", "2.1.4"
# gem "net-ssh-gateway", "1.1.0"
# gem "capistrano", "2.5.19"
# gem "capistrano-ext", "1.2.1"
# gem "activerecord", "~> 3.0.7"
# gem "ruby-mysql", "~> 2.9.4"
# gem "builder", "2.1.2"

group :test do
  gem "rspec", "2.6.0"
#  gem "activesupport", "3.0.7"
  gem "cucumber", "1.0.1"
#  gem "aruba", "~> 0.4.3"
#  gem "fakeweb", "~> 1.3"
#  gem "fakefs"
#  gem "akephalos", "0.2.5"
#  gem "Selenium", "1.1.14"
#  gem "selenium-client", "1.2.18"
#  gem "selenium-webdriver", "0.2.0"
  gem "capybara"
#  gem "capybara-envjs", "0.4.0"
  gem "capybara-webkit"
end

group :development do
#  gem "vagrant", "0.7.2"
#  gem "ghost", "0.2.8"
end