SandstormMedia:
  Semantic:
    PropertyMapping:
      SandstormMedia\MicroBlog\Domain\Model\BlogEntry:
        properties:
          text:
            type: sioc:content
          location:
            type: foaf:based_near
            linkify: true
            linkificationType: City
          text:
            type: sioc:content
            enrichText: true
