SandstormMedia:
  Semantic:
    PropertyMapping:
      SandstormMedia\MicroBlog\Domain\Model\BlogEntry:
        properties:
          text:
            type: sioc:content
          location:
            type: foaf:based_near
            externalResolver: SandstormMedia\Semantic\ExternalReference\DbpediaResolver
          text:
            type: sioc:content
            textEnricher: true
